import React, { useEffect, useState } from 'react';
import AlertTable from '../../components/alerts/AlertTable';
import Loader from '../../components/common/Loader';
import ErrorMessage from '../../components/common/ErrorMessage';
import { getAlerts } from '../../api/alertApi';

const Alerts = () => {
  const [alerts, setAlerts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    const load = async () => {
      try {
        setLoading(true);
        setError('');
        const data = await getAlerts();
        setAlerts(Array.isArray(data) ? data : []);
      } catch (err) {
        setError(err.response?.data?.detail || 'Unable to load alerts.');
      } finally {
        setLoading(false);
      }
    };
    load();
  }, []);

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-gray-100">System Alerts</h1>
        <p className="text-sm text-gray-400">Automated threat alerts generated by AI detection engine</p>
      </div>

      {error && <ErrorMessage message={error} />}
      {loading ? <Loader message="Loading alerts..." /> : <AlertTable alerts={alerts} />}
    </div>
  );
};

export default Alerts;
